//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int bookingid { get; set; }
        public int roomid { get; set; }
        public System.DateTime bookingdate { get; set; }
        public string bookingstatus { get; set; }
    
        public virtual room room { get; set; }
    }
}
