//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hotel()
        {
            this.rooms = new HashSet<room>();
        }
    
        public int hotelid { get; set; }
        public string hotelname { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public int pincode { get; set; }
        public int contactnumber { get; set; }
        public string contactperson { get; set; }
        public string website { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public bool isactive { get; set; }
        public bool isdelete { get; set; }
        public System.DateTime createddate { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public string createdby { get; set; }
        public string updatedby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<room> rooms { get; set; }
    }
}
