//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public room()
        {
            this.bookings = new HashSet<booking>();
        }
    
        public int roomid { get; set; }
        public int hotelid { get; set; }
        public string roomname { get; set; }
        public string roomcategory { get; set; }
        public decimal roomprice { get; set; }
        public bool isactive { get; set; }
        public bool isdelete { get; set; }
        public System.DateTime createddate { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public string createdby { get; set; }
        public string updatedby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
        public virtual hotel hotel { get; set; }
    }
}
